### ISSUE TITLE
Calamares ignores partition layout in partition.conf

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/calamares-settings-nitrux#10]
In our Calamares configuration, we include a custom `partition.conf` configuration file for the Partition module. We specify a custom partition layout; however, the structure is ignored by Calamares while the other settings are not.

Below are the contents of our file.

https://github.com/Nitrux/calamares-settings-nitrux/blob/3f93e75dd3eaf4c4a9b8aad36f1bbd1edb28c4a4/etc/calamares/modules/partition.conf#L1-L48

According to a few commenters on this [issue](https://github.com/calamares/calamares/issues/1759) at the Calamares bug tracker, this feature worked but suddenly didn't.

**Comment by santoshmahto7** [comment]
I was facing the same issue with calamares 3.2.52 but issue seems to be happening from > 3.2.39
I created a pull request which fixes this issue
https://github.com/calamares/calamares/pull/1903

**Comment by UriHerrera** [comment]
Closing as Calamares 3.2.56 does not have this problem anymore.

**Comment by UriHerrera** [comment]
Opening again as Calamares 3.2.61 ignores the partition layout.

**Comment by UriHerrera** [comment]
Closing as the feature is working but our configuration had the wrong indentation 🤷🏾
